#!/bin/bash

# Check the platform.
if [ "$(uname)" != "Darwin" ]; then
	echo "This script is for Mac only."
	exit 1
fi

# Run the configuration script first.
$(dirname $0)/configure || exit 1

# Create utility functions.
fail() {
	echo "$1"
	exit 1
}
cannot() {
	[ $? -eq 0 ] || fail "Cannot $1."
}
usage() {
	echo "usage: $0 [-m manifest-file] [-f front-end-directory] [-b back-end-file]"
	exit 2
}

# Collect command line parameters or provide defaults.
if [ $# -eq 0 ]; then
	MANIFEST_FILE=../panel.json
	FRONTEND_DIRECTORY=../my-extension
	BACKEND_FILE=../my-extension/services/backend.js
else
	ARGS=`getopt b:f:m:h $*`
	[ $? -eq 0 ] || usage
	set -- $ARGS
	for i; do
		case "$i" in
		-b)
			BACKEND_FILE="$2";
			[ -s "$BACKEND_FILE" ] || cannot "open back-end file '$BACKEND_FILE'"
			shift; shift;;
		-f)
			FRONTEND_DIRECTORY="$2";
			[ -d "$FRONTEND_DIRECTORY" ] || cannot "open front-end directory '$FRONTEND_DIRECTORY'"
			shift; shift;;
		-m)
			MANIFEST_FILE="$2";
			[ -s "$MANIFEST_FILE" ] || cannot "open manifest file '$MANIFEST_FILE'"
			shift; shift;;
		-h)
			usage;;
		--)
			shift;
			break;;
		esac
	done
	[ $# -eq 0 ] || usage
fi

# For the "hello world" extension, ensure service of the correct directory.
[ -d "$FRONTEND_DIRECTORY/public" ] && FRONTEND_DIRECTORY="$FRONTEND_DIRECTORY/public"

# If necessary, create a panel extension manifest file.
[ -n "$MANIFEST_FILE" ] || MANIFEST_FILE=../panel.json
if [ -s "$MANIFEST_FILE" ]; then
	echo "Using extension manifest in $MANIFEST_FILE."
else
	echo "Creating and using panel extension manifest in $MANIFEST_FILE."
	yarn create-manifest -t panel -o ../panel.json
fi

# Start new processes for the different aspects of running the rig.
NPROCESSES=0
if [ -z "$FRONTEND_DIRECTORY" ]; then
	echo "Front-end hosting is not being provided by the developer rig."
else
	echo "Hosting front-end in $FRONTEND_DIRECTORY."
	yarn host -d "$FRONTEND_DIRECTORY" -p 8080 -l &
	NPROCESSES=$(expr $NPROCESSES + 1)
fi
if [ -z "$BACKEND_FILE" ]; then
	echo "Back-end hosting is not being provided by the developer rig."
else
	echo "Hosting back-end in $BACKEND_FILE."
	node "$BACKEND_FILE" -l "$MANIFEST_FILE" &
	NPROCESSES=$(expr $NPROCESSES + 1)
fi
[ $NPROCESSES -gt 1 ] && ES=es
[ $NPROCESSES -gt 0 ] && echo "Started $NPROCESSES other process$ES to run the developer rig."
yarn start -l "$MANIFEST_FILE"
